language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - libxml2-utils
before_install:
- source ./src/ci/before_install.sh
script:
- "./src/ci/build.sh"
install:
- "true"
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/target/site/jacoco-aggregate/jacoco.xml
