version: 2.1

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.8

aliases:

  - &build_steps
    - checkout
    - run: java -version
    - run: ./mvnw clean install -Pci

jobs:
  
  jdk8:
    docker:
      - image: cimg/openjdk:8.0.322
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps
  
  jdk11:
    docker:
      - image: cimg/openjdk:11.0.13
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps
          
  jdk17:
    docker:
      - image: cimg/openjdk:17.0.3
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps

  snyk-scan:
    docker:
      - image: cimg/openjdk:21.0.0
    steps:
      - checkout
      - run: ./mvnw clean install -Pci
      - general-platform-helpers/step-load-dependencies
      - general-platform-helpers/step-run-snyk-monitor:
          scan-all-projects: false
          skip-unresolved: false
          run-on-non-main: true
          additional-arguments: "--maven-aggregate-project"

workflows:
  semgrep:
    jobs:
      - jdk17:
          requires:
            - cache-secrets
      - general-platform-helpers/job-semgrep-prepare:
          name: semgrep-prepare
      - general-platform-helpers/job-semgrep-scan:
          name: "Scan with Semgrep"
          requires:
            - semgrep-prepare
      - general-platform-helpers/job-snyk-prepare:
          name: prepare-snyk
          requires:
            - jdk17
      - snyk-scan:
          name: execute-snyk
          requires:
            - prepare-snyk
